/**
 * What arrives when somebody's credential is ready.
 *
 * It carries the badge — the face, but also the name, the one-liner and the
 * challenge placement, which is what makes it theirs rather than a photograph. The
 * card is still a thing you pick up and swing, so the email sends people
 * to the page where it hangs; what it shows is the printed object.
 *
 * The placement is stamped in the header as well, where a card carries its
 * own, so the sheet the email is laid out as is stamped like the sheet
 * inside it.
 */

import { buildDecisionEmail } from "@/lib/admin/decision-email";
import { emailAddresses } from "@/lib/emails/config";
import {
  button,
  command,
  emailShell,
  eyebrow,
  heading,
  paragraph,
  picture,
} from "@/lib/emails/layout";

export interface BadgeReadyEmailInput {
  readonly applicationId: string;
  readonly email: string;
  readonly firstName: string;
  /** The badge, already uploaded — a mail client cannot read a buffer. */
  readonly badgeUrl: string;
  /** Their best exact challenge placement, stamped where the card carries it. */
  readonly placement: string;
  /** Where the card itself hangs. */
  readonly badgePageUrl: string;
  /** Whether this is the automatic badge sent at acceptance. */
  readonly requiresConfirmation: boolean;
  /** Makes regenerated badge notifications independently deliverable. */
  readonly generationId: string;
  /** Present only for the default badge generated by an acceptance decision. */
  readonly notification?: {
    readonly kind: "acceptance";
    readonly message?: string;
  };
}

const SUBJECT = "Tu carnet de Hack the Andes está listo";

export const buildBadgeReadyEmail = (
  input: Omit<BadgeReadyEmailInput, "applicationId" | "email" | "generationId">,
): {
  readonly subject: string;
  readonly text: string;
  readonly html: string;
} => {
  if (input.notification?.kind === "acceptance") {
    return buildDecisionEmail({
      decision: "accepted",
      firstName: input.firstName,
      message: input.notification.message,
      badgeUrl: input.badgeUrl,
      badgePageUrl: input.badgePageUrl,
      placement: input.placement,
    });
  }

  const name = input.firstName.trim();
  const greeting = name ? `Hola ${name},` : "Hola,";
  let introduction =
    "Tu nuevo carnet ya está listo con los cambios que elegiste.";
  let body =
    "Puedes volver a personalizar el nombre, la foto, la presentación de una línea o el enlace del QR con andes badge regenerate.";
  let terminalCommand = "andes badge";
  let terminalInstruction =
    "Siguiente paso: consulta y comparte tu carnet con andes badge";
  if (input.requiresConfirmation) {
    introduction =
      "Tu carnet predeterminado ya está hecho con el nombre, la foto y la presentación que teníamos al aceptar tu postulación.";
    body =
      "Ejecuta andes confirm para cambiar el nombre del carnet, la foto o la presentación de una línea y generar uno nuevo. Completa el comando aunque quieras conservar este carnet: necesitamos tu nombre completo y DNI o pasaporte para autorizar tu ingreso al venue. Comparte también tu teléfono para que podamos contactarte por WhatsApp si necesitamos coordinar contigo.";
    terminalCommand = "andes confirm";
    terminalInstruction = "Confirmar, personalizar y regenerar: andes confirm";
  }
  let congratulation: string | undefined;
  if (input.placement.endsWith("· #01")) {
    congratulation = `¡Felicitaciones! Alcanzaste ${input.placement}; tu primer lugar en el challenge también aparece en el carnet.`;
  }
  const sharing =
    "Celebra este logro compartiendo tu carnet en LinkedIn e Instagram.";

  const textBlocks = [greeting, "", introduction];
  if (congratulation) textBlocks.push("", congratulation);
  textBlocks.push(
    "",
    body,
    "",
    sharing,
    "",
    `Ver mi carnet: ${input.badgePageUrl}`,
    terminalInstruction,
    "",
    "Nos vemos en la cima.",
    "— El equipo de Hack the Andes",
  );
  const text = textBlocks.join("\n");

  const blocks = [
    eyebrow("TU CARNET"),
    heading("Ya tienes carnet."),
    paragraph(greeting),
    paragraph(introduction),
  ];
  if (congratulation) blocks.push(paragraph(congratulation));
  blocks.push(
    picture(input.badgeUrl, "Tu carnet de Hack the Andes"),
    paragraph(body),
    paragraph(sharing),
    button("Ver mi carnet", input.badgePageUrl),
    command("Siguiente comando en tu terminal", terminalCommand),
  );

  const html = emailShell({
    subject: SUBJECT,
    preheader: "Tu foto está lista. El carnet completo te espera en el sitio.",
    stamp: input.placement,
    /*
      No range at the foot: the badge in the body has one printed on it,
      and the same drawing twice down one column reads as a repeated
      asset rather than as a motif.
    */
    ridge: false,
    blocks,
  });

  return { subject: SUBJECT, text, html };
};

export const sendBadgeReadyEmail = async (
  input: BadgeReadyEmailInput,
): Promise<void> => {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) throw new Error("RESEND_API_KEY is not configured");
  const email = buildBadgeReadyEmail(input);
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json",
      "idempotency-key": `participant-badge/${input.applicationId}/${input.generationId}`,
    },
    body: JSON.stringify({
      ...emailAddresses,
      to: [input.email],
      subject: email.subject,
      text: email.text,
      html: email.html,
    }),
  });
  if (response.ok) return;
  const body = (await response.json().catch(() => undefined)) as
    | { readonly message?: string }
    | undefined;
  throw new Error(body?.message ?? `Resend returned HTTP ${response.status}`);
};
