import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { slowServiceChallengeVersion } from "../packages/challenges-contract/src/slow-service";

const sourceDirectory = process.argv[2];
if (!sourceDirectory)
  throw new Error(
    "Usage: bun scripts/sync-slow-service-toolkit.ts <participant-safe-source-directory>",
  );
if (basename(resolve(sourceDirectory)) !== slowServiceChallengeVersion)
  throw new Error(
    `Use the approved src/${slowServiceChallengeVersion} whitelist, never a previous toolkit or frozen trial directory`,
  );
const destination = new URL(
  "../packages/challenges-contract/src/slow-service/",
  import.meta.url,
);
const whitelist = [
  ["README.participant.md", "README.md"],
  ["starter.js", "ledger.js"],
  ["contract.ts", ".kit/contract.ts"],
  ["runner.ts", ".kit/runner.ts"],
  ["public-benchmark.ts", ".kit/public-benchmark.ts"],
  ["participant-tests.ts", ".kit/ledger.test.ts"],
] as const;
const files: Record<string, string> = {};
for (const [source, target] of whitelist)
  files[target] = await readFile(resolve(sourceDirectory, source), "utf8");
files["package.json"] =
  `${JSON.stringify({ name: "slow-service-participant", private: true, type: "module", scripts: { test: "bun test ./.kit/ledger.test.ts", benchmark: "bun .kit/public-benchmark.ts" }, dependencies: { "quickjs-emscripten": "0.32.0" } }, null, 2)}\n`;
files["AGENTS.md"] =
  "# Participant workspace\n\nRead README.md. Edit ledger.js and add your own tests here. This directory contains only public challenge materials. Do not read private repositories, organizer files, other agents' worktrees, or past trial outputs. Preserve the provided .kit files. There is no hidden grader in this workspace.\n";
const contract = files[".kit/contract.ts"];
const runner = files[".kit/runner.ts"];
if (!contract || !runner) throw new Error("Missing public contract or runner");
// Only the package import differs. Bundler-safe dependency resolution is supplied by the public runner.
const replaceOnce = (
  source: string,
  original: string,
  replacement: string,
): string => {
  if (source.split(original).length !== 2)
    throw new Error("The public runner changed; review its framework adapters");
  return source.replace(original, replacement);
};
if (runner.includes("createRequire(import.meta.url).resolve"))
  throw new Error(
    "The public runner must preserve native dependency resolution in compiled builds",
  );
const webRunner = replaceOnce(
  runner,
  'from "./contract";',
  'from "@chofex/challenges-contract/slow-service/contract";',
);
await mkdir(destination, { recursive: true });
const artifacts = {
  "toolkit.generated.ts": `// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Participant files are literal source text.\n// Generated by scripts/sync-slow-service-toolkit.ts from the approved ${slowServiceChallengeVersion} participant-safe whitelist.\nexport const slowServiceToolkit: { readonly kind: "pending"; readonly version: ${JSON.stringify(slowServiceChallengeVersion)} } | { readonly kind: "ready"; readonly version: ${JSON.stringify(slowServiceChallengeVersion)}; readonly files: Readonly<Record<string, string>> } = { kind: "ready", version: ${JSON.stringify(slowServiceChallengeVersion)}, files: ${JSON.stringify(files, null, 2)} };\n`,
  "contract.ts": contract,
  "runner.ts": webRunner,
};
for (const [name, content] of Object.entries(artifacts))
  await writeFile(new URL(name, destination), content);
const format = Bun.spawn(
  [
    process.execPath,
    "x",
    "--bun",
    "@biomejs/biome",
    "check",
    "--write",
    ...Object.keys(artifacts).map((name) =>
      fileURLToPath(new URL(name, destination)),
    ),
  ],
  {
    cwd: fileURLToPath(new URL("../", import.meta.url)),
    stdout: "inherit",
    stderr: "inherit",
  },
);
if ((await format.exited) !== 0)
  throw new Error("Could not format generated toolkit");
